//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutricloud_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alimento_tipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alimento_tipo()
        {
            this.alimento = new HashSet<alimento>();
        }
    
        public int id_alimento_tipo { get; set; }
        public string alimento_tipo1 { get; set; }
        public string unidad_medida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alimento> alimento { get; set; }
    }
}
