//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutricloud_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alimento()
        {
            this.usuario_alimento = new HashSet<usuario_alimento>();
        }
    
        public int id_alimento { get; set; }
        public Nullable<int> nro { get; set; }
        public string alimento1 { get; set; }
        public Nullable<decimal> energia_kj { get; set; }
        public Nullable<decimal> energia_kcal { get; set; }
        public Nullable<decimal> sodio_mg { get; set; }
        public Nullable<decimal> potasio_mg { get; set; }
        public Nullable<decimal> calcio_mg { get; set; }
        public Nullable<decimal> fosforo_mg { get; set; }
        public Nullable<decimal> hierro_mg { get; set; }
        public Nullable<decimal> zinc_mg { get; set; }
        public Nullable<decimal> tiamina_mg { get; set; }
        public Nullable<decimal> rivoflavina_mg { get; set; }
        public Nullable<decimal> niacina_mg { get; set; }
        public Nullable<decimal> vitamina_c_mg { get; set; }
        public Nullable<decimal> colesterol_mg { get; set; }
        public Nullable<decimal> cenizas_g { get; set; }
        public Nullable<decimal> agua_g { get; set; }
        public Nullable<decimal> grasa_total_g { get; set; }
        public Nullable<decimal> carbohidratos_totales_g { get; set; }
        public Nullable<decimal> carbohidratos_disponibles_g { get; set; }
        public Nullable<decimal> ac_grasos_saturados_g { get; set; }
        public Nullable<decimal> ac_grasos_monoinsaturados_g { get; set; }
        public Nullable<decimal> ac_grasos_poliinsaturados_g { get; set; }
        public Nullable<decimal> fibra_dietetica_g { get; set; }
        public Nullable<decimal> proteinas_g { get; set; }
        public Nullable<decimal> agp_w6_g { get; set; }
        public Nullable<decimal> agp_w3_g { get; set; }
        public decimal porcion { get; set; }
        public int id_alimento_tipo { get; set; }
        public int id_alimento_genero { get; set; }
    
        public virtual alimento_genero alimento_genero { get; set; }
        public virtual alimento_tipo alimento_tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_alimento> usuario_alimento { get; set; }
    }
}
