//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutricloud_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consulta_mensaje
    {
        public int id_mensaje { get; set; }
        public string mensaje { get; set; }
        public System.DateTime f_mensaje { get; set; }
        public int id_consulta_conversacion { get; set; }
    
        public virtual consulta_conversacion consulta_conversacion { get; set; }
    }
}
