//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutricloud_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_alimento
    {
        public int id_usuario_alimento { get; set; }
        public int id_usuario { get; set; }
        public int id_alimento { get; set; }
        public int id_comida_tipo { get; set; }
        public int cantidad { get; set; }
        public int id_unidad_medida { get; set; }
    
        public virtual alimento alimento { get; set; }
        public virtual comida_tipo comida_tipo { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
